#ifndef NOVEL_PROJECT_ENUMS_H
#define NOVEL_PROJECT_ENUMS_H

#include <string.h>


enum type{NAME = 0, DESCRIPTION = 1, AUTHOR = 2, RATING = 3, POWER = 4, ACTION, DELETE, DELETE_LOWER, DELETE_UPPER, POWER_REASON, EDIT, SORT, ORDER};

char* mapTypeToString(int type);

#endif //NOVEL_PROJECT_ENUMS_H
